name: Java CI mit Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Repository auschecken
      - name: Repository laden
        uses: actions/checkout@v4

      # Cache für Maven-Dependencies

      # JDK-Setup
      - name: JDK-Setup für Maven-Build
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      # Maven-Build & Tests
      - name: Maven-Build & Tests
        run: mvn clean verify --batch-mode

      # JUnit Tests Berichte
      - name: JUnit Test Report
        if: always()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
        continue-on-error: true